CREATE TABLE Leadershipskills(
LeaderID INT NOT NULL
,Leader VARCHAR2(50)
,Sheep VARCHAR2(50)
,Hero VARCHAR2(50)
);

ALTER TABLE Leader ADD CONSTRAINT Leader_PK PRIMARY KEY(
Leader_ID
);


CREATE TABLE Email(
EmailID INT NOT NULL,


ALTER TABLE Email ADD CONSTRAINT Email_PK PRIMARY KEY(

Email_ID

);


CREATE TABLE Player(
PlayerID INT NOT NULL
,Name VARCHAR2(50)
,Skill VARCHAR2(50)
);

ALTER TABLE Player ADD CONSTRAINT Player_PK PRIMARY KEY(

Player_ID

);


CREATE TABLE Avatar(
Avatar_ID INT NOT NULL
,AvatarNum VARCHAR2 (50)
,Firstname VARCHAR2(50)
,DOB NUMBER (50)
,Strength VARCHAR2(50)
,Gender VARCHAR2(50)
);

ALTER TABLE Avatar ADD CONSTRAINT Avatar_PK PRIMARY KEY(
Avatar_ID
);



CREATE TABLE MasterAvatar(
MastAV_ID INT NOT NULL
,Initials VARCHAR2 (50)
,Sheep VARCHAR2 (50)
,Hero VARCHAR2 (50)
);

ALTER TABLE MastAV ADD CONSTRAINT MastAV_PK PRIMARY KEY(
MastAV_ID
);


CREATE TABLE SuperAvatar(
SuperAV_ID int,
Mentallychallenged VARCHAR2 (50),
Awake VARCHAR2 (50),
smart VARCHAR2 (50),
Genius VARCHAR2 (50) 
);
ALTER TABLE SuperAV ADD CONSTRAINT SuperAV_PK PRIMARY KEY(
SuperAV_ID
);


CREATE TABLE Species(
SpeciesID INT NOT NULL
Firstname VARCHAR2 (50), NOT NULL
Strengh VARCHAR2 (50), NOT NULL
Cost INT (50), NOT NULL
Pixie VARCHAR (50), NOT NULL
Goblin VARCHAR(50), NOT NULL

ALTER TABLE Species ADD CONSTRAINT Species_PK PRIMARY KEY(

Species_ID

);


CREATE TABLE Weapons(
WeaponID INT NOT NULL
Name VARCHAR2 (50), NOT NULL
Range VARCHAR2 (50), NOT NULL
Number of uses VARCHAR2 (50), NOT NULL
Damage factor VARCHAR2 (50), NOT NULL
Goblin VARCHAR(50), NOT NULL

ALTER TABLE Weapon ADD CONSTRAINT Weapon_PK PRIMARY KEY(

Weapon_ID

);


CREATE TABLE Children(
Child ID INT NOT NULL
Name VARCHAR2 (50), NOT NULL

ALTER TABLE Child ADD CONSTRAINT Child_PK PRIMARY KEY(
Child_ID
);


CREATE TABLE Parent(
Parent ID INT NOT NULL
Name VARCHAR2 (50), NOT NULL

ALTER TABLE Parent ADD CONSTRAINT Parent_PK PRIMARY KEY(
Parent_ID
);


CREATE TABLE Mega Avatar(
Mega AV ID INT NOT NULL,
Trickster VARCHAR2(50), NOT NULL
Conjurer VARCHAR2(50), NOT NULL
Magician VARCHAR2(50), NOT NULL
Wizard VARCHAR2(50), NOT NULL
Sorcerer VARCHAR2(50), NOT NULL

ALTER TABLE Mega AV ADD CONSTRAINT Mega AV_PK PRIMARY KEY(

MegaAV_ID

);

